// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketSystem.DAL.Data.Context;

#nullable disable

namespace TicketSystem.DAL.Migrations
{
    [DbContext(typeof(SystemContext))]
    [Migration("20240319114638_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketSystem.DAL.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("TicketSystem.DAL.Data.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 3, 4, 13, 46, 38, 308, DateTimeKind.Local).AddTicks(4647),
                            DepartmentId = 3,
                            Email = "user1@example.com",
                            IsClosed = false,
                            Severity = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 3, 9, 13, 46, 38, 308, DateTimeKind.Local).AddTicks(4714),
                            DepartmentId = 2,
                            Email = "user2@example.com",
                            IsClosed = true,
                            Severity = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 3, 3, 13, 46, 38, 308, DateTimeKind.Local).AddTicks(4717),
                            DepartmentId = 1,
                            Email = "user3@example.com",
                            IsClosed = false,
                            Severity = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 3, 8, 13, 46, 38, 308, DateTimeKind.Local).AddTicks(4719),
                            DepartmentId = 3,
                            Email = "user4@example.com",
                            IsClosed = false,
                            Severity = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 3, 5, 13, 46, 38, 308, DateTimeKind.Local).AddTicks(4721),
                            DepartmentId = 2,
                            Email = "user5@example.com",
                            IsClosed = true,
                            Severity = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 3, 12, 13, 46, 38, 308, DateTimeKind.Local).AddTicks(4725),
                            DepartmentId = 1,
                            Email = "user6@example.com",
                            IsClosed = true,
                            Severity = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 3, 15, 13, 46, 38, 308, DateTimeKind.Local).AddTicks(4727),
                            DepartmentId = 5,
                            Email = "user7@example.com",
                            IsClosed = true,
                            Severity = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 3, 7, 13, 46, 38, 308, DateTimeKind.Local).AddTicks(4729),
                            DepartmentId = 2,
                            Email = "user8@example.com",
                            IsClosed = false,
                            Severity = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 3, 6, 13, 46, 38, 308, DateTimeKind.Local).AddTicks(4731),
                            DepartmentId = 4,
                            Email = "user9@example.com",
                            IsClosed = false,
                            Severity = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 3, 10, 13, 46, 38, 308, DateTimeKind.Local).AddTicks(4734),
                            DepartmentId = 3,
                            Email = "user10@example.com",
                            IsClosed = true,
                            Severity = 2
                        });
                });

            modelBuilder.Entity("TicketSystem.DAL.Data.Models.Ticket", b =>
                {
                    b.HasOne("TicketSystem.DAL.Data.Models.Department", "Department")
                        .WithMany("Tickets")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TicketSystem.DAL.Data.Models.Department", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
